### ISSUE TITLE
Demo site not working due to Netlify change

### ISSUE THREAD

**Issue by LouOtway** [erikdstock/gatsby-theme-auth0-ts#19]
Since mid April all Netlify sites are now *.netlify.app. This means that all apps with redirect URs that still use *.netlify.com are broken.

I guess you need to update:

gatsby-theme-auth0-ts-example.netlify.com
to
gatsby-theme-auth0-ts-example.netlify.app

**Comment by erikdstock** [comment]
9 months late but thanks for the heads up @LouOtway - fixed.
